// Generates endgame mate drills (docs/backend/06 §6 rungs 1-2): random KQ-K and KR-K positions, kept only when the engine
// finds a forced mate in 1 or 2 and the first move is unique. Written into the puzzle shard format with `own: true`.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { Chess } from 'chess.js';
import { createEngineClient, type UciTransport } from '../src/core/engine/engineClient';

const require = createRequire(import.meta.url);
const engine = createEngineClient(async (): Promise<UciTransport> => {
  const e = await require('stockfish')(resolve('node_modules/stockfish/bin/stockfish-19-lite-single.js'));
  let cb: (l: string) => void = () => {};
  e.listener = (l: string) => cb(l);
  return { send: (c) => e.sendCommand(c), onLine: (f) => (cb = f), dispose: () => e.terminate?.() };
});
let s = 424242;
const rnd = () => (s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296;
const sq = () => `${'abcdefgh'[Math.floor(rnd() * 8)]}${1 + Math.floor(rnd() * 8)}`;
const adjacent = (a: string, b: string) =>
  Math.abs(a.charCodeAt(0) - b.charCodeAt(0)) <= 1 && Math.abs(+a[1] - +b[1]) <= 1;

async function build(piece: 'q' | 'r', skill: string, n: number) {
  const out: { id: string; fen: string; moves: string; rating: number; themes: string[]; own: true }[] = [];
  for (let tries = 0; tries < 3000 && out.length < n; tries++) {
    const [wk, wp, bk] = [sq(), sq(), sq()];
    if (new Set([wk, wp, bk]).size < 3 || adjacent(wk, bk)) continue;
    const c = new Chess();
    c.clear();
    c.put({ type: 'k', color: 'w' }, wk as never);
    c.put({ type: 'k', color: 'b' }, bk as never);
    c.put({ type: piece, color: 'w' }, wp as never);
    const fen = `${c.fen().split(' ').slice(0, 1)[0]} w - - 0 1`;
    let g: Chess;
    try {
      g = new Chess(fen);
    } catch {
      continue;
    }
    if (g.isGameOver() || g.inCheck()) continue;
    const r = await engine.analyse(fen, { depth: 14, multiPv: 2 });
    const [a, b] = r.lines;
    if (!a || a.mate === undefined || a.mate < 1 || a.mate > 2) continue;
    if (b && b.mate !== undefined && b.mate > 0 && b.mate <= a.mate) continue; // first move must be unique
    const moves = [a.pv[0], ...(a.mate === 2 ? [a.pv[1], a.pv[2]] : [])];
    out.push({
      id: `${skill}-${piece}-${out.length}`,
      fen,
      moves: moves.join(' '),
      rating: a.mate === 1 ? 450 : 650,
      themes: [a.mate === 1 ? 'mateIn1' : 'mateIn2', piece === 'q' ? 'kingAndQueen' : 'kingAndRook'],
      own: true,
    });
  }
  return out;
}

const q = await build('q', 'eg_basic_mates', 40);
const r = await build('r', 'eg_basic_mates', 40);
const all = [...q, ...r];
const split = (lo: number, hi: number) => all.filter((p) => p.rating >= lo && p.rating < hi);
mkdirSync('public/content/puzzles/eg_basic_mates', { recursive: true });
const prov = {
  source: 'Generated by tools/build-endgames.ts',
  license: 'own (positions generated, not copied)',
  engineVerified: true,
  engine: 'Stockfish 19 lite depth 14: forced mate in 1-2 with a unique first move',
  skill: 'eg_basic_mates',
};
const idx = JSON.parse(readFileSync('public/content/puzzles/index.json', 'utf8'));
idx.counts.eg_basic_mates = {};
for (const [band, lo, hi] of [['400-700', 400, 700]] as const) {
  const ps = split(lo, hi + 200); // both mate-in-1 and mate-in-2 positions live in the easiest band
  writeFileSync(
    `public/content/puzzles/eg_basic_mates/${band}.json`,
    JSON.stringify({ provenance: { ...prov, band }, puzzles: ps }),
  );
  idx.counts.eg_basic_mates[band] = ps.length;
}
writeFileSync('public/content/puzzles/index.json', JSON.stringify(idx, null, 1));
console.log('endgame drills:', q.length, 'queen,', r.length, 'rook');
process.exit(0);
